/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.tc.poc.dms.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DmsPoc service. Represents a row in the &quot;DMSPOC_DmsPoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.tc.poc.dms.model.impl.DmsPocModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.tc.poc.dms.model.impl.DmsPocImpl</code>.
 * </p>
 *
 * @author Manisha Gera
 * @see DmsPoc
 * @generated
 */
@ProviderType
public interface DmsPocModel
	extends BaseModel<DmsPoc>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dms poc model instance should use the {@link DmsPoc} interface instead.
	 */

	/**
	 * Returns the primary key of this dms poc.
	 *
	 * @return the primary key of this dms poc
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dms poc.
	 *
	 * @param primaryKey the primary key of this dms poc
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dms poc.
	 *
	 * @return the uuid of this dms poc
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dms poc.
	 *
	 * @param uuid the uuid of this dms poc
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this dms poc.
	 *
	 * @return the ID of this dms poc
	 */
	public long getId();

	/**
	 * Sets the ID of this dms poc.
	 *
	 * @param id the ID of this dms poc
	 */
	public void setId(long id);

	/**
	 * Returns the group ID of this dms poc.
	 *
	 * @return the group ID of this dms poc
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dms poc.
	 *
	 * @param groupId the group ID of this dms poc
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the org ID of this dms poc.
	 *
	 * @return the org ID of this dms poc
	 */
	public long getOrgId();

	/**
	 * Sets the org ID of this dms poc.
	 *
	 * @param orgId the org ID of this dms poc
	 */
	public void setOrgId(long orgId);

	/**
	 * Returns the company ID of this dms poc.
	 *
	 * @return the company ID of this dms poc
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dms poc.
	 *
	 * @param companyId the company ID of this dms poc
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dms poc.
	 *
	 * @return the user ID of this dms poc
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dms poc.
	 *
	 * @param userId the user ID of this dms poc
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dms poc.
	 *
	 * @return the user uuid of this dms poc
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dms poc.
	 *
	 * @param userUuid the user uuid of this dms poc
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dms poc.
	 *
	 * @return the user name of this dms poc
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dms poc.
	 *
	 * @param userName the user name of this dms poc
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dms poc.
	 *
	 * @return the create date of this dms poc
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dms poc.
	 *
	 * @param createDate the create date of this dms poc
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dms poc.
	 *
	 * @return the modified date of this dms poc
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dms poc.
	 *
	 * @param modifiedDate the modified date of this dms poc
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this dms poc.
	 *
	 * @return the modified by of this dms poc
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this dms poc.
	 *
	 * @param modifiedBy the modified by of this dms poc
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the modified by name of this dms poc.
	 *
	 * @return the modified by name of this dms poc
	 */
	@AutoEscape
	public String getModifiedByName();

	/**
	 * Sets the modified by name of this dms poc.
	 *
	 * @param modifiedByName the modified by name of this dms poc
	 */
	public void setModifiedByName(String modifiedByName);

	/**
	 * Returns the deleted of this dms poc.
	 *
	 * @return the deleted of this dms poc
	 */
	public boolean getDeleted();

	/**
	 * Returns <code>true</code> if this dms poc is deleted.
	 *
	 * @return <code>true</code> if this dms poc is deleted; <code>false</code> otherwise
	 */
	public boolean isDeleted();

	/**
	 * Sets whether this dms poc is deleted.
	 *
	 * @param deleted the deleted of this dms poc
	 */
	public void setDeleted(boolean deleted);

	/**
	 * Returns the repair order no of this dms poc.
	 *
	 * @return the repair order no of this dms poc
	 */
	@AutoEscape
	public String getRepairOrderNo();

	/**
	 * Sets the repair order no of this dms poc.
	 *
	 * @param repairOrderNo the repair order no of this dms poc
	 */
	public void setRepairOrderNo(String repairOrderNo);

	/**
	 * Returns the dealer code of this dms poc.
	 *
	 * @return the dealer code of this dms poc
	 */
	@AutoEscape
	public String getDealerCode();

	/**
	 * Sets the dealer code of this dms poc.
	 *
	 * @param dealerCode the dealer code of this dms poc
	 */
	public void setDealerCode(String dealerCode);

	/**
	 * Returns the authorised dealer info of this dms poc.
	 *
	 * @return the authorised dealer info of this dms poc
	 */
	@AutoEscape
	public String getAuthorisedDealerInfo();

	/**
	 * Sets the authorised dealer info of this dms poc.
	 *
	 * @param authorisedDealerInfo the authorised dealer info of this dms poc
	 */
	public void setAuthorisedDealerInfo(String authorisedDealerInfo);

	/**
	 * Returns the dealership name of this dms poc.
	 *
	 * @return the dealership name of this dms poc
	 */
	@AutoEscape
	public String getDealershipName();

	/**
	 * Sets the dealership name of this dms poc.
	 *
	 * @param dealershipName the dealership name of this dms poc
	 */
	public void setDealershipName(String dealershipName);

	/**
	 * Returns the dealership address of this dms poc.
	 *
	 * @return the dealership address of this dms poc
	 */
	@AutoEscape
	public String getDealershipAddress();

	/**
	 * Sets the dealership address of this dms poc.
	 *
	 * @param dealershipAddress the dealership address of this dms poc
	 */
	public void setDealershipAddress(String dealershipAddress);

	/**
	 * Returns the dealer ship phone no of this dms poc.
	 *
	 * @return the dealer ship phone no of this dms poc
	 */
	public long getDealerShipPhoneNo();

	/**
	 * Sets the dealer ship phone no of this dms poc.
	 *
	 * @param dealerShipPhoneNo the dealer ship phone no of this dms poc
	 */
	public void setDealerShipPhoneNo(long dealerShipPhoneNo);

	/**
	 * Returns the fax no of this dms poc.
	 *
	 * @return the fax no of this dms poc
	 */
	public long getFaxNo();

	/**
	 * Sets the fax no of this dms poc.
	 *
	 * @param faxNo the fax no of this dms poc
	 */
	public void setFaxNo(long faxNo);

	/**
	 * Returns the dealership email of this dms poc.
	 *
	 * @return the dealership email of this dms poc
	 */
	@AutoEscape
	public String getDealershipEmail();

	/**
	 * Sets the dealership email of this dms poc.
	 *
	 * @param dealershipEmail the dealership email of this dms poc
	 */
	public void setDealershipEmail(String dealershipEmail);

	/**
	 * Returns the gst of this dms poc.
	 *
	 * @return the gst of this dms poc
	 */
	@AutoEscape
	public String getGST();

	/**
	 * Sets the gst of this dms poc.
	 *
	 * @param GST the gst of this dms poc
	 */
	public void setGST(String GST);

	/**
	 * Returns the customer name of this dms poc.
	 *
	 * @return the customer name of this dms poc
	 */
	@AutoEscape
	public String getCustomerName();

	/**
	 * Sets the customer name of this dms poc.
	 *
	 * @param customerName the customer name of this dms poc
	 */
	public void setCustomerName(String customerName);

	/**
	 * Returns the customer address of this dms poc.
	 *
	 * @return the customer address of this dms poc
	 */
	@AutoEscape
	public String getCustomerAddress();

	/**
	 * Sets the customer address of this dms poc.
	 *
	 * @param customerAddress the customer address of this dms poc
	 */
	public void setCustomerAddress(String customerAddress);

	/**
	 * Returns the customer mobile no of this dms poc.
	 *
	 * @return the customer mobile no of this dms poc
	 */
	public long getCustomerMobileNo();

	/**
	 * Sets the customer mobile no of this dms poc.
	 *
	 * @param customerMobileNo the customer mobile no of this dms poc
	 */
	public void setCustomerMobileNo(long customerMobileNo);

	/**
	 * Returns the customer email address of this dms poc.
	 *
	 * @return the customer email address of this dms poc
	 */
	@AutoEscape
	public String getCustomerEmailAddress();

	/**
	 * Sets the customer email address of this dms poc.
	 *
	 * @param customerEmailAddress the customer email address of this dms poc
	 */
	public void setCustomerEmailAddress(String customerEmailAddress);

	/**
	 * Returns the contact person of this dms poc.
	 *
	 * @return the contact person of this dms poc
	 */
	@AutoEscape
	public String getContactPerson();

	/**
	 * Sets the contact person of this dms poc.
	 *
	 * @param contactPerson the contact person of this dms poc
	 */
	public void setContactPerson(String contactPerson);

	/**
	 * Returns the contact person phone of this dms poc.
	 *
	 * @return the contact person phone of this dms poc
	 */
	public long getContactPersonPhone();

	/**
	 * Sets the contact person phone of this dms poc.
	 *
	 * @param contactPersonPhone the contact person phone of this dms poc
	 */
	public void setContactPersonPhone(long contactPersonPhone);

	/**
	 * Returns the reg no of this dms poc.
	 *
	 * @return the reg no of this dms poc
	 */
	@AutoEscape
	public String getRegNo();

	/**
	 * Sets the reg no of this dms poc.
	 *
	 * @param regNo the reg no of this dms poc
	 */
	public void setRegNo(String regNo);

	/**
	 * Returns the vin of this dms poc.
	 *
	 * @return the vin of this dms poc
	 */
	@AutoEscape
	public String getVIN();

	/**
	 * Sets the vin of this dms poc.
	 *
	 * @param VIN the vin of this dms poc
	 */
	public void setVIN(String VIN);

	/**
	 * Returns the date of delivery of this dms poc.
	 *
	 * @return the date of delivery of this dms poc
	 */
	public Date getDateOfDelivery();

	/**
	 * Sets the date of delivery of this dms poc.
	 *
	 * @param dateOfDelivery the date of delivery of this dms poc
	 */
	public void setDateOfDelivery(Date dateOfDelivery);

	/**
	 * Returns the kms in of this dms poc.
	 *
	 * @return the kms in of this dms poc
	 */
	public long getKmsIn();

	/**
	 * Sets the kms in of this dms poc.
	 *
	 * @param kmsIn the kms in of this dms poc
	 */
	public void setKmsIn(long kmsIn);

	/**
	 * Returns the model of this dms poc.
	 *
	 * @return the model of this dms poc
	 */
	@AutoEscape
	public String getModel();

	/**
	 * Sets the model of this dms poc.
	 *
	 * @param model the model of this dms poc
	 */
	public void setModel(String model);

	/**
	 * Returns the engine no of this dms poc.
	 *
	 * @return the engine no of this dms poc
	 */
	@AutoEscape
	public String getEngineNo();

	/**
	 * Sets the engine no of this dms poc.
	 *
	 * @param engineNo the engine no of this dms poc
	 */
	public void setEngineNo(String engineNo);

	/**
	 * Returns the insurance policy no of this dms poc.
	 *
	 * @return the insurance policy no of this dms poc
	 */
	@AutoEscape
	public String getInsurancePolicyNo();

	/**
	 * Sets the insurance policy no of this dms poc.
	 *
	 * @param insurancePolicyNo the insurance policy no of this dms poc
	 */
	public void setInsurancePolicyNo(String insurancePolicyNo);

	/**
	 * Returns the insurance expiry date of this dms poc.
	 *
	 * @return the insurance expiry date of this dms poc
	 */
	public Date getInsuranceExpiryDate();

	/**
	 * Sets the insurance expiry date of this dms poc.
	 *
	 * @param insuranceExpiryDate the insurance expiry date of this dms poc
	 */
	public void setInsuranceExpiryDate(Date insuranceExpiryDate);

	/**
	 * Returns the rsa required of this dms poc.
	 *
	 * @return the rsa required of this dms poc
	 */
	public boolean getRsaRequired();

	/**
	 * Returns <code>true</code> if this dms poc is rsa required.
	 *
	 * @return <code>true</code> if this dms poc is rsa required; <code>false</code> otherwise
	 */
	public boolean isRsaRequired();

	/**
	 * Sets whether this dms poc is rsa required.
	 *
	 * @param rsaRequired the rsa required of this dms poc
	 */
	public void setRsaRequired(boolean rsaRequired);

	/**
	 * Returns the appointment type of this dms poc.
	 *
	 * @return the appointment type of this dms poc
	 */
	@AutoEscape
	public String getAppointmentType();

	/**
	 * Sets the appointment type of this dms poc.
	 *
	 * @param appointmentType the appointment type of this dms poc
	 */
	public void setAppointmentType(String appointmentType);

	/**
	 * Returns the order date in of this dms poc.
	 *
	 * @return the order date in of this dms poc
	 */
	public Date getOrderDateIn();

	/**
	 * Sets the order date in of this dms poc.
	 *
	 * @param orderDateIn the order date in of this dms poc
	 */
	public void setOrderDateIn(Date orderDateIn);

	/**
	 * Returns the order time in of this dms poc.
	 *
	 * @return the order time in of this dms poc
	 */
	public Date getOrderTimeIn();

	/**
	 * Sets the order time in of this dms poc.
	 *
	 * @param orderTimeIn the order time in of this dms poc
	 */
	public void setOrderTimeIn(Date orderTimeIn);

	/**
	 * Returns the service advisor of this dms poc.
	 *
	 * @return the service advisor of this dms poc
	 */
	@AutoEscape
	public String getServiceAdvisor();

	/**
	 * Sets the service advisor of this dms poc.
	 *
	 * @param serviceAdvisor the service advisor of this dms poc
	 */
	public void setServiceAdvisor(String serviceAdvisor);

	/**
	 * Returns the service advisor mobile no of this dms poc.
	 *
	 * @return the service advisor mobile no of this dms poc
	 */
	public long getServiceAdvisorMobileNo();

	/**
	 * Sets the service advisor mobile no of this dms poc.
	 *
	 * @param serviceAdvisorMobileNo the service advisor mobile no of this dms poc
	 */
	public void setServiceAdvisorMobileNo(long serviceAdvisorMobileNo);

	/**
	 * Returns the sold by dealer of this dms poc.
	 *
	 * @return the sold by dealer of this dms poc
	 */
	@AutoEscape
	public String getSoldByDealer();

	/**
	 * Sets the sold by dealer of this dms poc.
	 *
	 * @param soldByDealer the sold by dealer of this dms poc
	 */
	public void setSoldByDealer(String soldByDealer);

	/**
	 * Returns the customer mobility type of this dms poc.
	 *
	 * @return the customer mobility type of this dms poc
	 */
	@AutoEscape
	public String getCustomerMobilityType();

	/**
	 * Sets the customer mobility type of this dms poc.
	 *
	 * @param customerMobilityType the customer mobility type of this dms poc
	 */
	public void setCustomerMobilityType(String customerMobilityType);

	/**
	 * Returns the transaction no of this dms poc.
	 *
	 * @return the transaction no of this dms poc
	 */
	@AutoEscape
	public String getTransactionNo();

	/**
	 * Sets the transaction no of this dms poc.
	 *
	 * @param transactionNo the transaction no of this dms poc
	 */
	public void setTransactionNo(String transactionNo);

	/**
	 * Returns the reason for visit of this dms poc.
	 *
	 * @return the reason for visit of this dms poc
	 */
	@AutoEscape
	public String getReasonForVisit();

	/**
	 * Sets the reason for visit of this dms poc.
	 *
	 * @param reasonForVisit the reason for visit of this dms poc
	 */
	public void setReasonForVisit(String reasonForVisit);

	/**
	 * Returns the extended warranty of this dms poc.
	 *
	 * @return the extended warranty of this dms poc
	 */
	@AutoEscape
	public String getExtendedWarranty();

	/**
	 * Sets the extended warranty of this dms poc.
	 *
	 * @param extendedWarranty the extended warranty of this dms poc
	 */
	public void setExtendedWarranty(String extendedWarranty);

	/**
	 * Returns the service plan of this dms poc.
	 *
	 * @return the service plan of this dms poc
	 */
	@AutoEscape
	public String getServicePlan();

	/**
	 * Sets the service plan of this dms poc.
	 *
	 * @param servicePlan the service plan of this dms poc
	 */
	public void setServicePlan(String servicePlan);

	/**
	 * Returns the customer order description of this dms poc.
	 *
	 * @return the customer order description of this dms poc
	 */
	@AutoEscape
	public String getCustomerOrderDescription();

	/**
	 * Sets the customer order description of this dms poc.
	 *
	 * @param customerOrderDescription the customer order description of this dms poc
	 */
	public void setCustomerOrderDescription(String customerOrderDescription);

	/**
	 * Returns the complaint of this dms poc.
	 *
	 * @return the complaint of this dms poc
	 */
	@AutoEscape
	public String getComplaint();

	/**
	 * Sets the complaint of this dms poc.
	 *
	 * @param complaint the complaint of this dms poc
	 */
	public void setComplaint(String complaint);

	/**
	 * Returns the work to be done of this dms poc.
	 *
	 * @return the work to be done of this dms poc
	 */
	@AutoEscape
	public String getWorkToBeDone();

	/**
	 * Sets the work to be done of this dms poc.
	 *
	 * @param workToBeDone the work to be done of this dms poc
	 */
	public void setWorkToBeDone(String workToBeDone);

	/**
	 * Returns the instruction of this dms poc.
	 *
	 * @return the instruction of this dms poc
	 */
	@AutoEscape
	public String getInstruction();

	/**
	 * Sets the instruction of this dms poc.
	 *
	 * @param instruction the instruction of this dms poc
	 */
	public void setInstruction(String instruction);

	/**
	 * Returns the car picture of this dms poc.
	 *
	 * @return the car picture of this dms poc
	 */
	@AutoEscape
	public String getCarPicture();

	/**
	 * Sets the car picture of this dms poc.
	 *
	 * @param carPicture the car picture of this dms poc
	 */
	public void setCarPicture(String carPicture);

	/**
	 * Returns the x dent of this dms poc.
	 *
	 * @return the x dent of this dms poc
	 */
	@AutoEscape
	public String getXDent();

	/**
	 * Sets the x dent of this dms poc.
	 *
	 * @param xDent the x dent of this dms poc
	 */
	public void setXDent(String xDent);

	/**
	 * Returns the scratch of this dms poc.
	 *
	 * @return the scratch of this dms poc
	 */
	@AutoEscape
	public String getScratch();

	/**
	 * Sets the scratch of this dms poc.
	 *
	 * @param scratch the scratch of this dms poc
	 */
	public void setScratch(String scratch);

	/**
	 * Returns the body damage of this dms poc.
	 *
	 * @return the body damage of this dms poc
	 */
	@AutoEscape
	public String getBodyDamage();

	/**
	 * Sets the body damage of this dms poc.
	 *
	 * @param bodyDamage the body damage of this dms poc
	 */
	public void setBodyDamage(String bodyDamage);

	/**
	 * Returns the modification or non obm fittings of this dms poc.
	 *
	 * @return the modification or non obm fittings of this dms poc
	 */
	@AutoEscape
	public String getModificationOrNonOBMFittings();

	/**
	 * Sets the modification or non obm fittings of this dms poc.
	 *
	 * @param modificationOrNonOBMFittings the modification or non obm fittings of this dms poc
	 */
	public void setModificationOrNonOBMFittings(
		String modificationOrNonOBMFittings);

	/**
	 * Returns the tyre condition of this dms poc.
	 *
	 * @return the tyre condition of this dms poc
	 */
	@AutoEscape
	public String getTyreCondition();

	/**
	 * Sets the tyre condition of this dms poc.
	 *
	 * @param tyreCondition the tyre condition of this dms poc
	 */
	public void setTyreCondition(String tyreCondition);

	/**
	 * Returns the tread depth of this dms poc.
	 *
	 * @return the tread depth of this dms poc
	 */
	@AutoEscape
	public String getTreadDepth();

	/**
	 * Sets the tread depth of this dms poc.
	 *
	 * @param treadDepth the tread depth of this dms poc
	 */
	public void setTreadDepth(String treadDepth);

	/**
	 * Returns the front right of this dms poc.
	 *
	 * @return the front right of this dms poc
	 */
	@AutoEscape
	public String getFrontRight();

	/**
	 * Sets the front right of this dms poc.
	 *
	 * @param frontRight the front right of this dms poc
	 */
	public void setFrontRight(String frontRight);

	/**
	 * Returns the front left of this dms poc.
	 *
	 * @return the front left of this dms poc
	 */
	@AutoEscape
	public String getFrontLeft();

	/**
	 * Sets the front left of this dms poc.
	 *
	 * @param frontLeft the front left of this dms poc
	 */
	public void setFrontLeft(String frontLeft);

	/**
	 * Returns the rear right of this dms poc.
	 *
	 * @return the rear right of this dms poc
	 */
	@AutoEscape
	public String getRearRight();

	/**
	 * Sets the rear right of this dms poc.
	 *
	 * @param rearRight the rear right of this dms poc
	 */
	public void setRearRight(String rearRight);

	/**
	 * Returns the rear left of this dms poc.
	 *
	 * @return the rear left of this dms poc
	 */
	@AutoEscape
	public String getRearLeft();

	/**
	 * Sets the rear left of this dms poc.
	 *
	 * @param rearLeft the rear left of this dms poc
	 */
	public void setRearLeft(String rearLeft);

	/**
	 * Returns the windows glazzing of this dms poc.
	 *
	 * @return the windows glazzing of this dms poc
	 */
	@AutoEscape
	public String getWindowsGlazzing();

	/**
	 * Sets the windows glazzing of this dms poc.
	 *
	 * @param windowsGlazzing the windows glazzing of this dms poc
	 */
	public void setWindowsGlazzing(String windowsGlazzing);

	/**
	 * Returns the wiper blades of this dms poc.
	 *
	 * @return the wiper blades of this dms poc
	 */
	@AutoEscape
	public String getWiperBlades();

	/**
	 * Sets the wiper blades of this dms poc.
	 *
	 * @param wiperBlades the wiper blades of this dms poc
	 */
	public void setWiperBlades(String wiperBlades);

	/**
	 * Returns the lights of this dms poc.
	 *
	 * @return the lights of this dms poc
	 */
	@AutoEscape
	public String getLights();

	/**
	 * Sets the lights of this dms poc.
	 *
	 * @param lights the lights of this dms poc
	 */
	public void setLights(String lights);

	/**
	 * Returns the exhaust system of this dms poc.
	 *
	 * @return the exhaust system of this dms poc
	 */
	@AutoEscape
	public String getExhaustSystem();

	/**
	 * Sets the exhaust system of this dms poc.
	 *
	 * @param exhaustSystem the exhaust system of this dms poc
	 */
	public void setExhaustSystem(String exhaustSystem);

	/**
	 * Returns the underbody of this dms poc.
	 *
	 * @return the underbody of this dms poc
	 */
	@AutoEscape
	public String getUnderbody();

	/**
	 * Sets the underbody of this dms poc.
	 *
	 * @param underbody the underbody of this dms poc
	 */
	public void setUnderbody(String underbody);

	/**
	 * Returns the engine compartment of this dms poc.
	 *
	 * @return the engine compartment of this dms poc
	 */
	@AutoEscape
	public String getEngineCompartment();

	/**
	 * Sets the engine compartment of this dms poc.
	 *
	 * @param engineCompartment the engine compartment of this dms poc
	 */
	public void setEngineCompartment(String engineCompartment);

	/**
	 * Returns the washing of this dms poc.
	 *
	 * @return the washing of this dms poc
	 */
	@AutoEscape
	public String getWashing();

	/**
	 * Sets the washing of this dms poc.
	 *
	 * @param washing the washing of this dms poc
	 */
	public void setWashing(String washing);

	/**
	 * Returns the oil level of this dms poc.
	 *
	 * @return the oil level of this dms poc
	 */
	@AutoEscape
	public String getOilLevel();

	/**
	 * Sets the oil level of this dms poc.
	 *
	 * @param oilLevel the oil level of this dms poc
	 */
	public void setOilLevel(String oilLevel);

	/**
	 * Returns the coolant of this dms poc.
	 *
	 * @return the coolant of this dms poc
	 */
	@AutoEscape
	public String getCoolant();

	/**
	 * Sets the coolant of this dms poc.
	 *
	 * @param coolant the coolant of this dms poc
	 */
	public void setCoolant(String coolant);

	/**
	 * Returns the windshield washer of this dms poc.
	 *
	 * @return the windshield washer of this dms poc
	 */
	@AutoEscape
	public String getWindshieldWasher();

	/**
	 * Sets the windshield washer of this dms poc.
	 *
	 * @param windshieldWasher the windshield washer of this dms poc
	 */
	public void setWindshieldWasher(String windshieldWasher);

	/**
	 * Returns the brakes of this dms poc.
	 *
	 * @return the brakes of this dms poc
	 */
	@AutoEscape
	public String getBrakes();

	/**
	 * Sets the brakes of this dms poc.
	 *
	 * @param brakes the brakes of this dms poc
	 */
	public void setBrakes(String brakes);

	/**
	 * Returns the axle of this dms poc.
	 *
	 * @return the axle of this dms poc
	 */
	@AutoEscape
	public String getAxle();

	/**
	 * Sets the axle of this dms poc.
	 *
	 * @param axle the axle of this dms poc
	 */
	public void setAxle(String axle);

	/**
	 * Returns the monograms of this dms poc.
	 *
	 * @return the monograms of this dms poc
	 */
	@AutoEscape
	public String getMonograms();

	/**
	 * Sets the monograms of this dms poc.
	 *
	 * @param monograms the monograms of this dms poc
	 */
	public void setMonograms(String monograms);

	/**
	 * Returns the polishing of this dms poc.
	 *
	 * @return the polishing of this dms poc
	 */
	@AutoEscape
	public String getPolishing();

	/**
	 * Sets the polishing of this dms poc.
	 *
	 * @param polishing the polishing of this dms poc
	 */
	public void setPolishing(String polishing);

	/**
	 * Returns the fuel of this dms poc.
	 *
	 * @return the fuel of this dms poc
	 */
	@AutoEscape
	public String getFuel();

	/**
	 * Sets the fuel of this dms poc.
	 *
	 * @param fuel the fuel of this dms poc
	 */
	public void setFuel(String fuel);

	/**
	 * Returns the owners manual of this dms poc.
	 *
	 * @return the owners manual of this dms poc
	 */
	@AutoEscape
	public String getOwnersManual();

	/**
	 * Sets the owners manual of this dms poc.
	 *
	 * @param ownersManual the owners manual of this dms poc
	 */
	public void setOwnersManual(String ownersManual);

	/**
	 * Returns the ser sche maintenance manual of this dms poc.
	 *
	 * @return the ser sche maintenance manual of this dms poc
	 */
	@AutoEscape
	public String getSerScheMaintenanceManual();

	/**
	 * Sets the ser sche maintenance manual of this dms poc.
	 *
	 * @param serScheMaintenanceManual the ser sche maintenance manual of this dms poc
	 */
	public void setSerScheMaintenanceManual(String serScheMaintenanceManual);

	/**
	 * Returns the infotainment mmi navig manual of this dms poc.
	 *
	 * @return the infotainment mmi navig manual of this dms poc
	 */
	@AutoEscape
	public String getInfotainmentMmiNavigManual();

	/**
	 * Sets the infotainment mmi navig manual of this dms poc.
	 *
	 * @param infotainmentMmiNavigManual the infotainment mmi navig manual of this dms poc
	 */
	public void setInfotainmentMmiNavigManual(
		String infotainmentMmiNavigManual);

	/**
	 * Returns the ext warranty book of this dms poc.
	 *
	 * @return the ext warranty book of this dms poc
	 */
	@AutoEscape
	public String getExtWarrantyBook();

	/**
	 * Sets the ext warranty book of this dms poc.
	 *
	 * @param extWarrantyBook the ext warranty book of this dms poc
	 */
	public void setExtWarrantyBook(String extWarrantyBook);

	/**
	 * Returns the quick reference guide of this dms poc.
	 *
	 * @return the quick reference guide of this dms poc
	 */
	@AutoEscape
	public String getQuickReferenceGuide();

	/**
	 * Sets the quick reference guide of this dms poc.
	 *
	 * @param quickReferenceGuide the quick reference guide of this dms poc
	 */
	public void setQuickReferenceGuide(String quickReferenceGuide);

	/**
	 * Returns the spare wheel of this dms poc.
	 *
	 * @return the spare wheel of this dms poc
	 */
	@AutoEscape
	public String getSpareWheel();

	/**
	 * Sets the spare wheel of this dms poc.
	 *
	 * @param spareWheel the spare wheel of this dms poc
	 */
	public void setSpareWheel(String spareWheel);

	/**
	 * Returns the jack tool kits of this dms poc.
	 *
	 * @return the jack tool kits of this dms poc
	 */
	@AutoEscape
	public String getJackToolKits();

	/**
	 * Sets the jack tool kits of this dms poc.
	 *
	 * @param jackToolKits the jack tool kits of this dms poc
	 */
	public void setJackToolKits(String jackToolKits);

	/**
	 * Returns the floor mat of this dms poc.
	 *
	 * @return the floor mat of this dms poc
	 */
	@AutoEscape
	public String getFloorMat();

	/**
	 * Sets the floor mat of this dms poc.
	 *
	 * @param floorMat the floor mat of this dms poc
	 */
	public void setFloorMat(String floorMat);

	/**
	 * Returns the mud flaps of this dms poc.
	 *
	 * @return the mud flaps of this dms poc
	 */
	@AutoEscape
	public String getMudFlaps();

	/**
	 * Sets the mud flaps of this dms poc.
	 *
	 * @param mudFlaps the mud flaps of this dms poc
	 */
	public void setMudFlaps(String mudFlaps);

	/**
	 * Returns the warning triangle of this dms poc.
	 *
	 * @return the warning triangle of this dms poc
	 */
	@AutoEscape
	public String getWarningTriangle();

	/**
	 * Sets the warning triangle of this dms poc.
	 *
	 * @param warningTriangle the warning triangle of this dms poc
	 */
	public void setWarningTriangle(String warningTriangle);

	/**
	 * Returns the first aid kit of this dms poc.
	 *
	 * @return the first aid kit of this dms poc
	 */
	@AutoEscape
	public String getFirstAidKit();

	/**
	 * Sets the first aid kit of this dms poc.
	 *
	 * @param firstAidKit the first aid kit of this dms poc
	 */
	public void setFirstAidKit(String firstAidKit);

	/**
	 * Returns the no of keys of this dms poc.
	 *
	 * @return the no of keys of this dms poc
	 */
	public long getNoOfKeys();

	/**
	 * Sets the no of keys of this dms poc.
	 *
	 * @param noOfKeys the no of keys of this dms poc
	 */
	public void setNoOfKeys(long noOfKeys);

	/**
	 * Returns the other loose items of this dms poc.
	 *
	 * @return the other loose items of this dms poc
	 */
	@AutoEscape
	public String getOtherLooseItems();

	/**
	 * Sets the other loose items of this dms poc.
	 *
	 * @param otherLooseItems the other loose items of this dms poc
	 */
	public void setOtherLooseItems(String otherLooseItems);

	/**
	 * Returns the financial information of this dms poc.
	 *
	 * @return the financial information of this dms poc
	 */
	@AutoEscape
	public String getFinancialInformation();

	/**
	 * Sets the financial information of this dms poc.
	 *
	 * @param financialInformation the financial information of this dms poc
	 */
	public void setFinancialInformation(String financialInformation);

	/**
	 * Returns the mode of payment of this dms poc.
	 *
	 * @return the mode of payment of this dms poc
	 */
	@AutoEscape
	public String getModeOfPayment();

	/**
	 * Sets the mode of payment of this dms poc.
	 *
	 * @param modeOfPayment the mode of payment of this dms poc
	 */
	public void setModeOfPayment(String modeOfPayment);

	/**
	 * Returns the estimated cost of this dms poc.
	 *
	 * @return the estimated cost of this dms poc
	 */
	public long getEstimatedCost();

	/**
	 * Sets the estimated cost of this dms poc.
	 *
	 * @param estimatedCost the estimated cost of this dms poc
	 */
	public void setEstimatedCost(long estimatedCost);

	/**
	 * Returns the taxes as applicable of this dms poc.
	 *
	 * @return the taxes as applicable of this dms poc
	 */
	@AutoEscape
	public String getTaxesAsApplicable();

	/**
	 * Sets the taxes as applicable of this dms poc.
	 *
	 * @param taxesAsApplicable the taxes as applicable of this dms poc
	 */
	public void setTaxesAsApplicable(String taxesAsApplicable);

	/**
	 * Returns the estimated date of delivery of this dms poc.
	 *
	 * @return the estimated date of delivery of this dms poc
	 */
	public Date getEstimatedDateOfDelivery();

	/**
	 * Sets the estimated date of delivery of this dms poc.
	 *
	 * @param estimatedDateOfDelivery the estimated date of delivery of this dms poc
	 */
	public void setEstimatedDateOfDelivery(Date estimatedDateOfDelivery);

	/**
	 * Returns the estimated delivery time of this dms poc.
	 *
	 * @return the estimated delivery time of this dms poc
	 */
	@AutoEscape
	public String getEstimatedDeliveryTime();

	/**
	 * Sets the estimated delivery time of this dms poc.
	 *
	 * @param estimatedDeliveryTime the estimated delivery time of this dms poc
	 */
	public void setEstimatedDeliveryTime(String estimatedDeliveryTime);

	/**
	 * Returns the labor estimate of this dms poc.
	 *
	 * @return the labor estimate of this dms poc
	 */
	public long getLaborEstimate();

	/**
	 * Sets the labor estimate of this dms poc.
	 *
	 * @param laborEstimate the labor estimate of this dms poc
	 */
	public void setLaborEstimate(long laborEstimate);

	/**
	 * Returns the parts of this dms poc.
	 *
	 * @return the parts of this dms poc
	 */
	public long getParts();

	/**
	 * Sets the parts of this dms poc.
	 *
	 * @param parts the parts of this dms poc
	 */
	public void setParts(long parts);

	/**
	 * Returns the terms and conditions of this dms poc.
	 *
	 * @return the terms and conditions of this dms poc
	 */
	@AutoEscape
	public String getTermsAndConditions();

	/**
	 * Sets the terms and conditions of this dms poc.
	 *
	 * @param termsAndConditions the terms and conditions of this dms poc
	 */
	public void setTermsAndConditions(String termsAndConditions);

	/**
	 * Returns the grant my consent of this dms poc.
	 *
	 * @return the grant my consent of this dms poc
	 */
	@AutoEscape
	public String getGrantMyConsent();

	/**
	 * Sets the grant my consent of this dms poc.
	 *
	 * @param grantMyConsent the grant my consent of this dms poc
	 */
	public void setGrantMyConsent(String grantMyConsent);

	/**
	 * Returns the service advisot signature of this dms poc.
	 *
	 * @return the service advisot signature of this dms poc
	 */
	@AutoEscape
	public String getServiceAdvisotSignature();

	/**
	 * Sets the service advisot signature of this dms poc.
	 *
	 * @param serviceAdvisotSignature the service advisot signature of this dms poc
	 */
	public void setServiceAdvisotSignature(String serviceAdvisotSignature);

	/**
	 * Returns the customer signature of this dms poc.
	 *
	 * @return the customer signature of this dms poc
	 */
	@AutoEscape
	public String getCustomerSignature();

	/**
	 * Sets the customer signature of this dms poc.
	 *
	 * @param customerSignature the customer signature of this dms poc
	 */
	public void setCustomerSignature(String customerSignature);

	/**
	 * Returns the remarks area of this dms poc.
	 *
	 * @return the remarks area of this dms poc
	 */
	@AutoEscape
	public String getRemarksArea();

	/**
	 * Sets the remarks area of this dms poc.
	 *
	 * @param remarksArea the remarks area of this dms poc
	 */
	public void setRemarksArea(String remarksArea);

	/**
	 * Returns the terms strictly of this dms poc.
	 *
	 * @return the terms strictly of this dms poc
	 */
	@AutoEscape
	public String getTermsStrictly();

	/**
	 * Sets the terms strictly of this dms poc.
	 *
	 * @param termsStrictly the terms strictly of this dms poc
	 */
	public void setTermsStrictly(String termsStrictly);

	/**
	 * Returns the workshop copy of this dms poc.
	 *
	 * @return the workshop copy of this dms poc
	 */
	@AutoEscape
	public String getWorkshopCopy();

	/**
	 * Sets the workshop copy of this dms poc.
	 *
	 * @param workshopCopy the workshop copy of this dms poc
	 */
	public void setWorkshopCopy(String workshopCopy);

	/**
	 * Returns the version of this dms poc.
	 *
	 * @return the version of this dms poc
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this dms poc.
	 *
	 * @param version the version of this dms poc
	 */
	public void setVersion(String version);

	/**
	 * Returns the customer waiting of this dms poc.
	 *
	 * @return the customer waiting of this dms poc
	 */
	public boolean getCustomerWaiting();

	/**
	 * Returns <code>true</code> if this dms poc is customer waiting.
	 *
	 * @return <code>true</code> if this dms poc is customer waiting; <code>false</code> otherwise
	 */
	public boolean isCustomerWaiting();

	/**
	 * Sets whether this dms poc is customer waiting.
	 *
	 * @param customerWaiting the customer waiting of this dms poc
	 */
	public void setCustomerWaiting(boolean customerWaiting);

	/**
	 * Returns the campaign of this dms poc.
	 *
	 * @return the campaign of this dms poc
	 */
	@AutoEscape
	public String getCampaign();

	/**
	 * Sets the campaign of this dms poc.
	 *
	 * @param campaign the campaign of this dms poc
	 */
	public void setCampaign(String campaign);

	/**
	 * Returns the diss no of this dms poc.
	 *
	 * @return the diss no of this dms poc
	 */
	@AutoEscape
	public String getDissNo();

	/**
	 * Sets the diss no of this dms poc.
	 *
	 * @param dissNo the diss no of this dms poc
	 */
	public void setDissNo(String dissNo);

	/**
	 * Returns the descriptive information of this dms poc.
	 *
	 * @return the descriptive information of this dms poc
	 */
	@AutoEscape
	public String getDescriptiveInformation();

	/**
	 * Sets the descriptive information of this dms poc.
	 *
	 * @param descriptiveInformation the descriptive information of this dms poc
	 */
	public void setDescriptiveInformation(String descriptiveInformation);

	/**
	 * Returns the time start of this dms poc.
	 *
	 * @return the time start of this dms poc
	 */
	@AutoEscape
	public String getTimeStart();

	/**
	 * Sets the time start of this dms poc.
	 *
	 * @param timeStart the time start of this dms poc
	 */
	public void setTimeStart(String timeStart);

	/**
	 * Returns the time stop of this dms poc.
	 *
	 * @return the time stop of this dms poc
	 */
	@AutoEscape
	public String getTimeStop();

	/**
	 * Sets the time stop of this dms poc.
	 *
	 * @param timeStop the time stop of this dms poc
	 */
	public void setTimeStop(String timeStop);

	/**
	 * Returns the name of technician of this dms poc.
	 *
	 * @return the name of technician of this dms poc
	 */
	@AutoEscape
	public String getNameOfTechnician();

	/**
	 * Sets the name of technician of this dms poc.
	 *
	 * @param nameOfTechnician the name of technician of this dms poc
	 */
	public void setNameOfTechnician(String nameOfTechnician);

	/**
	 * Returns the technician signature of this dms poc.
	 *
	 * @return the technician signature of this dms poc
	 */
	@AutoEscape
	public String getTechnicianSignature();

	/**
	 * Sets the technician signature of this dms poc.
	 *
	 * @param technicianSignature the technician signature of this dms poc
	 */
	public void setTechnicianSignature(String technicianSignature);

	/**
	 * Returns the inventory parts json str of this dms poc.
	 *
	 * @return the inventory parts json str of this dms poc
	 */
	@AutoEscape
	public String getInventoryPartsJSONStr();

	/**
	 * Sets the inventory parts json str of this dms poc.
	 *
	 * @param inventoryPartsJSONStr the inventory parts json str of this dms poc
	 */
	public void setInventoryPartsJSONStr(String inventoryPartsJSONStr);

	/**
	 * Returns the part number of this dms poc.
	 *
	 * @return the part number of this dms poc
	 */
	@AutoEscape
	public String getPartNumber();

	/**
	 * Sets the part number of this dms poc.
	 *
	 * @param partNumber the part number of this dms poc
	 */
	public void setPartNumber(String partNumber);

	/**
	 * Returns the part description of this dms poc.
	 *
	 * @return the part description of this dms poc
	 */
	@AutoEscape
	public String getPartDescription();

	/**
	 * Sets the part description of this dms poc.
	 *
	 * @param partDescription the part description of this dms poc
	 */
	public void setPartDescription(String partDescription);

	/**
	 * Returns the part catagory of this dms poc.
	 *
	 * @return the part catagory of this dms poc
	 */
	@AutoEscape
	public String getPartCatagory();

	/**
	 * Sets the part catagory of this dms poc.
	 *
	 * @param partCatagory the part catagory of this dms poc
	 */
	public void setPartCatagory(String partCatagory);

	/**
	 * Returns the internal parts order of this dms poc.
	 *
	 * @return the internal parts order of this dms poc
	 */
	@AutoEscape
	public String getInternalPartsOrder();

	/**
	 * Sets the internal parts order of this dms poc.
	 *
	 * @param internalPartsOrder the internal parts order of this dms poc
	 */
	public void setInternalPartsOrder(String internalPartsOrder);

	/**
	 * Returns the part quantity of this dms poc.
	 *
	 * @return the part quantity of this dms poc
	 */
	@AutoEscape
	public String getPartQuantity();

	/**
	 * Sets the part quantity of this dms poc.
	 *
	 * @param partQuantity the part quantity of this dms poc
	 */
	public void setPartQuantity(String partQuantity);

	/**
	 * Returns the part rate of this dms poc.
	 *
	 * @return the part rate of this dms poc
	 */
	@AutoEscape
	public String getPartRate();

	/**
	 * Sets the part rate of this dms poc.
	 *
	 * @param partRate the part rate of this dms poc
	 */
	public void setPartRate(String partRate);

	/**
	 * Returns the part cost of this dms poc.
	 *
	 * @return the part cost of this dms poc
	 */
	@AutoEscape
	public String getPartCost();

	/**
	 * Sets the part cost of this dms poc.
	 *
	 * @param partCost the part cost of this dms poc
	 */
	public void setPartCost(String partCost);

	/**
	 * Returns the part total of this dms poc.
	 *
	 * @return the part total of this dms poc
	 */
	@AutoEscape
	public String getPartTotal();

	/**
	 * Sets the part total of this dms poc.
	 *
	 * @param partTotal the part total of this dms poc
	 */
	public void setPartTotal(String partTotal);

	/**
	 * Returns the parts json str of this dms poc.
	 *
	 * @return the parts json str of this dms poc
	 */
	@AutoEscape
	public String getPartsJSONStr();

	/**
	 * Sets the parts json str of this dms poc.
	 *
	 * @param partsJSONStr the parts json str of this dms poc
	 */
	public void setPartsJSONStr(String partsJSONStr);

	/**
	 * Returns the labour description of this dms poc.
	 *
	 * @return the labour description of this dms poc
	 */
	@AutoEscape
	public String getLabourDescription();

	/**
	 * Sets the labour description of this dms poc.
	 *
	 * @param labourDescription the labour description of this dms poc
	 */
	public void setLabourDescription(String labourDescription);

	/**
	 * Returns the labour catagory of this dms poc.
	 *
	 * @return the labour catagory of this dms poc
	 */
	@AutoEscape
	public String getLabourCatagory();

	/**
	 * Sets the labour catagory of this dms poc.
	 *
	 * @param labourCatagory the labour catagory of this dms poc
	 */
	public void setLabourCatagory(String labourCatagory);

	/**
	 * Returns the labour code of this dms poc.
	 *
	 * @return the labour code of this dms poc
	 */
	@AutoEscape
	public String getLabourCode();

	/**
	 * Sets the labour code of this dms poc.
	 *
	 * @param labourCode the labour code of this dms poc
	 */
	public void setLabourCode(String labourCode);

	/**
	 * Returns the time unit of this dms poc.
	 *
	 * @return the time unit of this dms poc
	 */
	@AutoEscape
	public String getTimeUnit();

	/**
	 * Sets the time unit of this dms poc.
	 *
	 * @param timeUnit the time unit of this dms poc
	 */
	public void setTimeUnit(String timeUnit);

	/**
	 * Returns the hours of this dms poc.
	 *
	 * @return the hours of this dms poc
	 */
	@AutoEscape
	public String getHours();

	/**
	 * Sets the hours of this dms poc.
	 *
	 * @param hours the hours of this dms poc
	 */
	public void setHours(String hours);

	/**
	 * Returns the labour rate of this dms poc.
	 *
	 * @return the labour rate of this dms poc
	 */
	@AutoEscape
	public String getLabourRate();

	/**
	 * Sets the labour rate of this dms poc.
	 *
	 * @param labourRate the labour rate of this dms poc
	 */
	public void setLabourRate(String labourRate);

	/**
	 * Returns the labour cost of this dms poc.
	 *
	 * @return the labour cost of this dms poc
	 */
	public long getLabourCost();

	/**
	 * Sets the labour cost of this dms poc.
	 *
	 * @param labourCost the labour cost of this dms poc
	 */
	public void setLabourCost(long labourCost);

	/**
	 * Returns the labour total of this dms poc.
	 *
	 * @return the labour total of this dms poc
	 */
	public long getLabourTotal();

	/**
	 * Sets the labour total of this dms poc.
	 *
	 * @param labourTotal the labour total of this dms poc
	 */
	public void setLabourTotal(long labourTotal);

	/**
	 * Returns the labour json str of this dms poc.
	 *
	 * @return the labour json str of this dms poc
	 */
	@AutoEscape
	public String getLabourJSONStr();

	/**
	 * Sets the labour json str of this dms poc.
	 *
	 * @param labourJSONStr the labour json str of this dms poc
	 */
	public void setLabourJSONStr(String labourJSONStr);

	/**
	 * Returns the additional repairs req desc of this dms poc.
	 *
	 * @return the additional repairs req desc of this dms poc
	 */
	@AutoEscape
	public String getAdditionalRepairsReqDesc();

	/**
	 * Sets the additional repairs req desc of this dms poc.
	 *
	 * @param additionalRepairsReqDesc the additional repairs req desc of this dms poc
	 */
	public void setAdditionalRepairsReqDesc(String additionalRepairsReqDesc);

	/**
	 * Returns the additional repairs req part of this dms poc.
	 *
	 * @return the additional repairs req part of this dms poc
	 */
	@AutoEscape
	public String getAdditionalRepairsReqPart();

	/**
	 * Sets the additional repairs req part of this dms poc.
	 *
	 * @param additionalRepairsReqPart the additional repairs req part of this dms poc
	 */
	public void setAdditionalRepairsReqPart(String additionalRepairsReqPart);

	/**
	 * Returns the additional repairs req labour of this dms poc.
	 *
	 * @return the additional repairs req labour of this dms poc
	 */
	@AutoEscape
	public String getAdditionalRepairsReqLabour();

	/**
	 * Sets the additional repairs req labour of this dms poc.
	 *
	 * @param additionalRepairsReqLabour the additional repairs req labour of this dms poc
	 */
	public void setAdditionalRepairsReqLabour(
		String additionalRepairsReqLabour);

	/**
	 * Returns the additional repairs req auth of this dms poc.
	 *
	 * @return the additional repairs req auth of this dms poc
	 */
	@AutoEscape
	public String getAdditionalRepairsReqAuth();

	/**
	 * Sets the additional repairs req auth of this dms poc.
	 *
	 * @param additionalRepairsReqAuth the additional repairs req auth of this dms poc
	 */
	public void setAdditionalRepairsReqAuth(String additionalRepairsReqAuth);

	/**
	 * Returns the additional repairs req dt of this dms poc.
	 *
	 * @return the additional repairs req dt of this dms poc
	 */
	public Date getAdditionalRepairsReqDT();

	/**
	 * Sets the additional repairs req dt of this dms poc.
	 *
	 * @param additionalRepairsReqDT the additional repairs req dt of this dms poc
	 */
	public void setAdditionalRepairsReqDT(Date additionalRepairsReqDT);

	/**
	 * Returns the road test km out of this dms poc.
	 *
	 * @return the road test km out of this dms poc
	 */
	public long getRoadTestKmOut();

	/**
	 * Sets the road test km out of this dms poc.
	 *
	 * @param roadTestKmOut the road test km out of this dms poc
	 */
	public void setRoadTestKmOut(long roadTestKmOut);

	/**
	 * Returns the road test km in of this dms poc.
	 *
	 * @return the road test km in of this dms poc
	 */
	public long getRoadTestKmIn();

	/**
	 * Sets the road test km in of this dms poc.
	 *
	 * @param roadTestKmIn the road test km in of this dms poc
	 */
	public void setRoadTestKmIn(long roadTestKmIn);

	/**
	 * Returns the all jobs attended of this dms poc.
	 *
	 * @return the all jobs attended of this dms poc
	 */
	public boolean getAllJobsAttended();

	/**
	 * Returns <code>true</code> if this dms poc is all jobs attended.
	 *
	 * @return <code>true</code> if this dms poc is all jobs attended; <code>false</code> otherwise
	 */
	public boolean isAllJobsAttended();

	/**
	 * Sets whether this dms poc is all jobs attended.
	 *
	 * @param allJobsAttended the all jobs attended of this dms poc
	 */
	public void setAllJobsAttended(boolean allJobsAttended);

	/**
	 * Returns the accessories setting as original of this dms poc.
	 *
	 * @return the accessories setting as original of this dms poc
	 */
	public boolean getAccessoriesSettingAsOriginal();

	/**
	 * Returns <code>true</code> if this dms poc is accessories setting as original.
	 *
	 * @return <code>true</code> if this dms poc is accessories setting as original; <code>false</code> otherwise
	 */
	public boolean isAccessoriesSettingAsOriginal();

	/**
	 * Sets whether this dms poc is accessories setting as original.
	 *
	 * @param accessoriesSettingAsOriginal the accessories setting as original of this dms poc
	 */
	public void setAccessoriesSettingAsOriginal(
		boolean accessoriesSettingAsOriginal);

	/**
	 * Returns the road test signature of this dms poc.
	 *
	 * @return the road test signature of this dms poc
	 */
	@AutoEscape
	public String getRoadTestSignature();

	/**
	 * Sets the road test signature of this dms poc.
	 *
	 * @param roadTestSignature the road test signature of this dms poc
	 */
	public void setRoadTestSignature(String roadTestSignature);

	/**
	 * Returns the road test date of this dms poc.
	 *
	 * @return the road test date of this dms poc
	 */
	public Date getRoadTestDate();

	/**
	 * Sets the road test date of this dms poc.
	 *
	 * @param roadTestDate the road test date of this dms poc
	 */
	public void setRoadTestDate(Date roadTestDate);

	/**
	 * Returns the interiors of this dms poc.
	 *
	 * @return the interiors of this dms poc
	 */
	public boolean getInteriors();

	/**
	 * Returns <code>true</code> if this dms poc is interiors.
	 *
	 * @return <code>true</code> if this dms poc is interiors; <code>false</code> otherwise
	 */
	public boolean isInteriors();

	/**
	 * Sets whether this dms poc is interiors.
	 *
	 * @param interiors the interiors of this dms poc
	 */
	public void setInteriors(boolean interiors);

	/**
	 * Returns the interiors polishing of this dms poc.
	 *
	 * @return the interiors polishing of this dms poc
	 */
	public boolean getInteriorsPolishing();

	/**
	 * Returns <code>true</code> if this dms poc is interiors polishing.
	 *
	 * @return <code>true</code> if this dms poc is interiors polishing; <code>false</code> otherwise
	 */
	public boolean isInteriorsPolishing();

	/**
	 * Sets whether this dms poc is interiors polishing.
	 *
	 * @param interiorsPolishing the interiors polishing of this dms poc
	 */
	public void setInteriorsPolishing(boolean interiorsPolishing);

	/**
	 * Returns the exteriors of this dms poc.
	 *
	 * @return the exteriors of this dms poc
	 */
	public boolean getExteriors();

	/**
	 * Returns <code>true</code> if this dms poc is exteriors.
	 *
	 * @return <code>true</code> if this dms poc is exteriors; <code>false</code> otherwise
	 */
	public boolean isExteriors();

	/**
	 * Sets whether this dms poc is exteriors.
	 *
	 * @param exteriors the exteriors of this dms poc
	 */
	public void setExteriors(boolean exteriors);

	/**
	 * Returns the exteriors polishing of this dms poc.
	 *
	 * @return the exteriors polishing of this dms poc
	 */
	public boolean getExteriorsPolishing();

	/**
	 * Returns <code>true</code> if this dms poc is exteriors polishing.
	 *
	 * @return <code>true</code> if this dms poc is exteriors polishing; <code>false</code> otherwise
	 */
	public boolean isExteriorsPolishing();

	/**
	 * Sets whether this dms poc is exteriors polishing.
	 *
	 * @param exteriorsPolishing the exteriors polishing of this dms poc
	 */
	public void setExteriorsPolishing(boolean exteriorsPolishing);

	/**
	 * Returns the vacuum cleaned of this dms poc.
	 *
	 * @return the vacuum cleaned of this dms poc
	 */
	public boolean getVacuumCleaned();

	/**
	 * Returns <code>true</code> if this dms poc is vacuum cleaned.
	 *
	 * @return <code>true</code> if this dms poc is vacuum cleaned; <code>false</code> otherwise
	 */
	public boolean isVacuumCleaned();

	/**
	 * Sets whether this dms poc is vacuum cleaned.
	 *
	 * @param vacuumCleaned the vacuum cleaned of this dms poc
	 */
	public void setVacuumCleaned(boolean vacuumCleaned);

	/**
	 * Returns the washing checker signature of this dms poc.
	 *
	 * @return the washing checker signature of this dms poc
	 */
	@AutoEscape
	public String getWashingCheckerSignature();

	/**
	 * Sets the washing checker signature of this dms poc.
	 *
	 * @param washingCheckerSignature the washing checker signature of this dms poc
	 */
	public void setWashingCheckerSignature(String washingCheckerSignature);

	/**
	 * Returns the status of this dms poc.
	 *
	 * @return the status of this dms poc
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this dms poc.
	 *
	 * @param status the status of this dms poc
	 */
	public void setStatus(String status);

	/**
	 * Returns the to show of this dms poc.
	 *
	 * @return the to show of this dms poc
	 */
	public boolean getToShow();

	/**
	 * Returns <code>true</code> if this dms poc is to show.
	 *
	 * @return <code>true</code> if this dms poc is to show; <code>false</code> otherwise
	 */
	public boolean isToShow();

	/**
	 * Sets whether this dms poc is to show.
	 *
	 * @param toShow the to show of this dms poc
	 */
	public void setToShow(boolean toShow);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DmsPoc dmsPoc);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DmsPoc> toCacheModel();

	@Override
	public DmsPoc toEscapedModel();

	@Override
	public DmsPoc toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}